export const sagaActions = {
  FETCH_EMPLOYEES_SAGA: "FETCH_EMPLOYEES_SAGA",
  DELETE_EMPLOYEE_SAGA:"DELETE_EMPLOYEE_SAGA",
  UPDATE_EMPLOYEE_SAGA:"UPDATE_EMPLOYEE_SAGA",
  CREATE_EMPLOYEE_SAGA :'CREATE_EMPLOYEE_SAGA',
};
